# Generated by Django 2.2 on 2020-09-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='jenis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
