# Generated by Django 2.2 on 2020-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20200910_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
