# Generated by Django 2.2 on 2020-09-10 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_auto_20200910_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='waktu',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
