# Generated by Django 2.2 on 2020-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField(default='')),
                ('telp', models.CharField(max_length=255)),
                ('norek', models.CharField(max_length=100)),
            ],
        ),
    ]
