# Generated by Django 2.2 on 2020-09-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembeli',
            name='norek',
        ),
    ]
